// Generated by CoffeeScript 1.12.1
(function() {
  var error, net, rethinkdb;

  net = require('./net');

  rethinkdb = require('./ast');

  error = require('./errors');

  rethinkdb.connect = net.connect;

  rethinkdb.Error = error;

  rethinkdb._bluebird = require('bluebird');

  module.exports = rethinkdb;

  module.exports.net = net;

}).call(this);
